# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2413c688d55473eaa6c110bccaee1bd0e5f95abdde0f6a97762c243d0b5fbb80817d4676262179ed4b7ac10ac363520fb89c52aeadea08283968d8824f152fcf

test:
  secret_key_base: 4fd11f189b7884d8e42d26da1c1d27a862449a76239c51a813d6074019ecb95614bc65fe7180781abeda33084423e28b40171a43235eb9aad0fba0bf72535cf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
